# -*- coding: utf-8 -*-
require "colorize"
require 'command_line/global'

task :default do
  system "rake -T"
end

namespace :develop do
  desc "clean up dirs"
  task :tidy do # any name on task_name
    # your code goes
    ['**/check_log.yaml',
     './check_log.yaml',
     '**/word_log.yaml',
    './word_log.yaml'].each do |file|
      p comm = "rm -f #{file}"
      system comm
    end
    exit
  end
  desc "mk sample tgz"
  task :mk_tgz do # any name on task_name
    # your code goes
    t_name= "abbrev_sample.tgz"
    dirs = "abbrev_yamls"
    p comm = "tar -cvf #{t_name} #{dirs}"
    system comm
    exit
  end

end
